server:
  port: 9002
  shutdown: graceful # ??? ??? ???
  netty:
    connection-timeout: 2s # ??? TCP ??? ???? ?? ???? ??
    idle-timeout: 15s # ???? ???? ?? ?? TCP ??? ?? ?? ???? ??

spring:
  application:
    name: oeder-service
  lifecycle:
    timeout-per-shutdown-phace: 15s # 15? ?? ??? ?? ??? ??